### PR TITLE
Supports .NET Standard

### PR DESCRIPTION
**Pull request by xin9le**
# Summary
Currently, CloudStructures targets only .NET Framework. This pull-request provides .NET Standard support.

# Mainly Changes
This pull-request contains **many breaking changes** like following.

## Refactoring
- Add `RedisBit` (cut out from `RedisString`)
- Add `RedisGeo`
- Remove `RedisClass`
- Remove `ServerSelector`
- Remove `TraceHelper`
- Remove config file loading feature
- Remove Glimpse support
- Remove `RedisSubject` (currently not support, might add this)
- `RedisSettings` and `RedisGroup` are now merged `RedisConnection`

## Performance Improvement
- Modify redis structures (ex. `RedisString`, `RedisDictionary`) from `class` to `struct`
- No boxing and zero heap allocation `ValueConverter`
- Provide `MessagePackConverter` using [MessagePack for C#](https://github.com/neuecc/MessagePack-CSharp)
- Provide `Utf8JsonConverter` using [Utf8Json](https://github.com/neuecc/Utf8Json)

### CODE REVIEW

**Comment by neuecc** [comment]
Why is `Utf8JsonConverter` changed to `internal`?

**Comment by xin9le** [comment]
Because, `Utf8JsonConverter` is used only default fallback converter.

**Comment by xin9le** [comment]
I fixed it because `Utf8JsonConverter` can set only `null` argument is too bad.

**Comment by neuecc** [comment]
Okay, thanks!
I've sent contibutor mail, you can do anything:)
also NuGet owner.

**Comment by neuecc** [comment]
so please upload new lib!

**Comment by xin9le** [comment]
Thank you for your kindness review :)
I'll upload new version library in a few days.

**Pull request merged**
